name: Lint
on:
  push:
    paths:
      - '**.lua'
      - '.github/workflows/lint.yml'
  pull_request_target:
    paths:
      - '**.lua'
      - '.github/workflows/lint.yml'
  workflow_dispatch:

jobs:
  lint:
    uses: CachopoRP/gh-actions/.github/workflows/lint.yml@main
